
services:
  server:
    container_name: sandbox_frontend_container
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 6002:6002
    extra_hosts:
       - "host.docker.internal:host-gateway"
    restart: always
